
- include_tasks:                'tasks/common/install_packages.yml'
  vars:
    install_packages:           "{{ install_packages_first }}"
- include_tasks:                'tasks/common/install_packages.yml'
